name: KICS Scan

on:
  issues:
    types: [opened]

  pull_request: 
    types: [opened, synchronize]
    branches:
      - main

  workflow_dispatch:
    inputs:
      FAIL_ON:
        description: 'The severity level to fail the scan (e.g., high, medium, low)'
        default: ''
        required: false  # Fail on is optional
      PATH:
        description: 'paths to a file or directories to scan, comma-separated list'
        default: './'
        required: true  # True on is not optional
      EXCLUDE_PATH:
        description: 'paths to a file or directories to exclude, comma-separated list'
        required: false
        default: './.github'
    
jobs:
  kics-scan:
    permissions:
      actions: read
      issues: write
      contents: read
      pull-requests: write
      security-events: write
    runs-on: ubuntu-latest

    steps:
      # Checkout the source code
      - name: Checkout source code
        uses: actions/checkout@v4

      # Generate the results directory
      - name: Generate results-dir
        run: mkdir -p results-dir
      
      # Run KICS
      - name: Start IaC Scan (KICS Scan)
        uses: checkmarx/kics-github-action@v2.0.0
        id: kics-scan
        continue-on-error: true
        with:
          path: ${{ input.PATH }}
          fail_on: ${{ input.FAIL_ON }}
          exclude_paths: ${{ EXCLUDE_PATH }}
          output_formats: 'json,sarif,html,csv'
          
      # Upload SARIF file
      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results-dir/results.sarif

      # Upload files to workflow run
      - name: Upload KICS Scan Reports as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kics-reports
          path: |
            ./results-dir/results.sarif
            ./results-dir/results.json
            ./results-dir/results.html
            ./results-dir/results.csv
